steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'VITE_API_URL=${_VITE_API_URL}'
      - '-t'
      - '${_IMAGE_NAME}'
      - '-f'
      - 'Dockerfile'
      - '.'
images:
  - '${_IMAGE_NAME}'
substitutions:
  _VITE_API_URL: 'http://localhost:5001/api'
  _IMAGE_NAME: 'gcr.io/${PROJECT_ID}/ci-newsletter-frontend'
