FROM python:3.9-slim 

WORKDIR /app

COPY . /app

# Copy the requirements file
COPY cloud_run_job/requirements.txt .

RUN pip install -e .

# Install dependencies
RUN pip install -r requirements.txt

# Set the entrypoint for the container
CMD ["python", "src/services/news_fetcher.py"] 